[package]
name = "proxyconf"
version = "0.2.3"
authors = ["Julien Roncaglia <julien@roncaglia.fr>"]
license = "MIT"
keywords = ["windows", "docker", "proxy", "config", "cli"]
categories = ["command-line-utilities", "os::windows-apis"]
homepage = "https://github.com/vbfox/proxyconf"
repository = "https://github.com/vbfox/proxyconf"
description = """
Windows proxy configuration from the command line.
"""
readme = "README.md"
edition = "2018"
rust-version = "1.85"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.6.7", features = ["cargo"] }
thiserror = "2.0.20"

[target.'cfg(windows)'.dependencies]
winreg = "0.56.0"

[dev-dependencies]
hex = "0.4.3"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1

[lib]
name = "proxyconf"
path = "src/proxyconf/lib.rs"

[[bin]]
name = "proxyconf"
test = false
doc = false
